[build]
  command = "node build-redirects.js"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "PORT"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
